@baseUrl = http://localhost:8080

# Health Check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "New Room",
    "description": "This is a new room created via API."
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Create Question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "What is the capital of France?"
}

###

# Get Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions